In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [101]:
from sklearn.datasets import load_iris
iris=sns.load_dataset('iris')
iris.head(5)

,sepal_length,sepal_width,petal_length,petal_width,species
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa


In [102]:
iris.describe()

,sepal_length,sepal_width,petal_length,petal_width
count,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333
std,0.828066,0.435866,1.765298,0.762238
min,4.300000,2.000000,1.000000,0.100000
25%,5.100000,2.800000,1.600000,0.300000
50%,5.800000,3.000000,4.350000,1.300000
75%,6.400000,3.300000,5.100000,1.800000
max,7.900000,4.400000,6.900000,2.500000


In [103]:
iris.isna().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [105]:
iris.groupby('species').count()

,sepal_length,sepal_width,petal_length,petal_width
species,,,,
setosa,50,50,50,50
versicolor,50,50,50,50
virginica,50,50,50,50


In [30]:
data=np.array(iris.iloc[:,0:4])
data

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [32]:
data.mean(axis=0)

array([5.84333333, 3.05733333, 3.758     , 1.19933333])

In [41]:
np.std(data,axis=0)

array([0.82530129, 0.43441097, 1.75940407, 0.75969263])

In [64]:
def sta(x):
    y=(x-x.mean())/x.std()
    return y

c=np.zeros((4,len(data)))
for i in [0,1,2,3]:
    c[i]=sta(data[:,i])
c

array([[-9.00681170e-01, -1.14301691e+00, -1.38535265e+00,
        -1.50652052e+00, -1.02184904e+00, -5.37177559e-01,
        -1.50652052e+00, -1.02184904e+00, -1.74885626e+00,
        -1.14301691e+00, -5.37177559e-01, -1.26418478e+00,
        -1.26418478e+00, -1.87002413e+00, -5.25060772e-02,
        -1.73673948e-01, -5.37177559e-01, -9.00681170e-01,
        -1.73673948e-01, -9.00681170e-01, -5.37177559e-01,
        -9.00681170e-01, -1.50652052e+00, -9.00681170e-01,
        -1.26418478e+00, -1.02184904e+00, -1.02184904e+00,
        -7.79513300e-01, -7.79513300e-01, -1.38535265e+00,
        -1.26418478e+00, -5.37177559e-01, -7.79513300e-01,
        -4.16009689e-01, -1.14301691e+00, -1.02184904e+00,
        -4.16009689e-01, -1.14301691e+00, -1.74885626e+00,
        -9.00681170e-01, -1.02184904e+00, -1.62768839e+00,
        -1.74885626e+00, -1.02184904e+00, -9.00681170e-01,
        -1.26418478e+00, -9.00681170e-01, -1.50652052e+00,
        -6.58345429e-01, -1.02184904e+00,  1.40150837e+0

In [69]:
c.reshape(3,50,4)

array([[[-9.00681170e-01, -1.14301691e+00, -1.38535265e+00,
         -1.50652052e+00],
        [-1.02184904e+00, -5.37177559e-01, -1.50652052e+00,
         -1.02184904e+00],
        [-1.74885626e+00, -1.14301691e+00, -5.37177559e-01,
         -1.26418478e+00],
        [-1.26418478e+00, -1.87002413e+00, -5.25060772e-02,
         -1.73673948e-01],
        [-5.37177559e-01, -9.00681170e-01, -1.73673948e-01,
         -9.00681170e-01],
        [-5.37177559e-01, -9.00681170e-01, -1.50652052e+00,
         -9.00681170e-01],
        [-1.26418478e+00, -1.02184904e+00, -1.02184904e+00,
         -7.79513300e-01],
        [-7.79513300e-01, -1.38535265e+00, -1.26418478e+00,
         -5.37177559e-01],
        [-7.79513300e-01, -4.16009689e-01, -1.14301691e+00,
         -1.02184904e+00],
        [-4.16009689e-01, -1.14301691e+00, -1.74885626e+00,
         -9.00681170e-01],
        [-1.02184904e+00, -1.62768839e+00, -1.74885626e+00,
         -1.02184904e+00],
        [-9.00681170e-01, -1.26418478e+00, 

In [109]:
iris=sns.load_dataset('iris')
iris.loc[:,'size_category']=pd.cut(iris.loc[:,'petal_length'],bins=[0,2.5,5,max(iris.loc[:,'petal_length'])],labels=['small','medium','large'])
iris.head(5)

,sepal_length,sepal_width,petal_length,petal_width,species,size_category
0,5.1,3.5,1.4,0.2,setosa,small
1,4.9,3.0,1.4,0.2,setosa,small
2,4.7,3.2,1.3,0.2,setosa,small
3,4.6,3.1,1.5,0.2,setosa,small
4,5.0,3.6,1.4,0.2,setosa,small


In [92]:
iris.iloc[:,0:5].groupby('species').agg(['mean','min','max'])

sepal_length           sepal_width           petal_length       \
                   mean  min  max        mean  min  max         mean  min   
species                                                                     
setosa            5.006  4.3  5.8       3.428  2.3  4.4        1.462  1.0   
versicolor        5.936  4.9  7.0       2.770  2.0  3.4        4.260  3.0   
virginica         6.588  4.9  7.9       2.974  2.2  3.8        5.552  4.5   

                petal_width            
            max        mean  min  max  
species                                
setosa      1.9       0.246  0.1  0.6  
versicolor  5.1       1.326  1.0  1.8  
virginica   6.9       2.026  1.4  2.5

In [97]:
iris.loc[:,'sepal_ratio']=iris.loc[:,'sepal_length']/iris.loc[:,'sepal_width']
iris.loc[:,'petal_ratio']=iris.loc[:,'petal_length']/iris.loc[:,'petal_width']
iris.iloc[:,-2:].corr()

,sepal_ratio,petal_ratio
sepal_ratio,1.000000,-0.611992
petal_ratio,-0.611992,1.000000


In [111]:
pd.pivot_table(iris,index='species',columns='size_category',values='petal_length',aggfunc='count')

C:\Users\dell\AppData\Local\Temp\ipykernel_33056\557236075.py:1: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  pd.pivot_table(iris,index='species',columns='size_category',values='petal_length',aggfunc='count')


size_category,small,medium,large
species,,,
setosa,50,0,0
versicolor,0,49,1
virginica,0,9,41


In [9]:
import numpy as np
import pandas as pd
data = np.array([
    ["Alice", 25, 90],
    ["Bob", 35, 85],
    ["Charlie", 28, 95],
    ["David", 45, 80],
    ["Eve", 22, 92]
])
df = pd.DataFrame(
    data,
    columns=['name', 'age', 'score'],  # 列名（3个，与数据列数匹配）
    index=np.arange(0, 5, 1)  # 索引0-4（5个，与数据行数匹配，修正你的4→5）
)
df['age']=df['age'].astype(int)
df['score']=df['score'].astype(int)

def dis(x):
    if x > 50:
        return '老年'
    elif x < 30:
        return '青年'
    else:
        return '中年'


# 3. map函数应用+深拷贝（修正：函数调用，统一引号）
age_new = df['age'].map(dis).copy()  # 正确，保留

age_new

0    青年
1    中年
2    青年
3    中年
4    青年
Name: age, dtype: object