In [2]:
import numpy as np

In [4]:
print(np.__version__)

2.2.6


# creat array  

In [6]:
list=[1,2,4,5,6,2,6]
print(list)

[1, 2, 4, 5, 6, 2, 6]


In [8]:
arr=np.array(list)
print(arr)

[1 2 4 5 6 2 6]


In [10]:
arr.shape

(7,)

In [12]:
arr.ndim

1

In [14]:
l1=[[1,2,3],[4,5,6]]
arr1=np.array(l1)
print(arr1)

[[1 2 3]
 [4 5 6]]


In [18]:
l2=[[[1,2,3],[8,5,6],[7,0,6]],[[4,5,6],[6,4,9],[2,5,2]]]
arr2=np.array(l2)
print(arr2)

[[[1 2 3]
  [8 5 6]
  [7 0 6]]

 [[4 5 6]
  [6 4 9]
  [2 5 2]]]


In [20]:
arr2.shape

(2, 3, 3)

In [22]:
np.random.seed(123)
ran_arr=np.random.random((2,3))
print(ran_arr)

[[0.69646919 0.28613933 0.22685145]
 [0.55131477 0.71946897 0.42310646]]


In [24]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [28]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [36]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

# array_index

In [59]:
inc=[1,3]
print(arr[inc])
print(arr[-2])

[2 5]
2


In [64]:
con=arr>2
print(con)
print(arr[con])

[False False  True  True  True False  True]
[4 5 6 6]


In [66]:
con=(arr>2)&(arr<6)
print(con)
print(arr[con])

[False False  True  True False False False]
[4 5]


In [74]:
print(arr[arr>3])

[4 5 6 6]


# array_slicing    

In [77]:
arr1=np.array([1,2,3,4,5,6,7,8,9])
print(arr1[2:4])

[3 4]


In [81]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2[:2,:2])
print(arr2[1:,2])

[[1 2]
 [4 5]]
[6 9]


# array_manipulation

In [90]:
arr=np.arange(12)
print(arr)

# reshape
re_arr=np.reshape(arr,(3,4))
print(re_arr)
re_shape=np.reshape(arr,(2,2,3))
print(re_shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [91]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
arr=np.concatenate((arr1,arr2))
print(arr)

[1 2 3 4 5 6]


In [97]:
arr3=np.array([[1,2],[5,6]])
arr4=np.array([[4,5],[7,8]])
con=np.concatenate((arr3,arr4),axis=1)
print(con)
con=np.concatenate((arr3,arr4),axis=0)
print(con)

[[1 2 4 5]
 [5 6 7 8]]
[[1 2]
 [5 6]
 [4 5]
 [7 8]]


In [100]:
con=np.vstack((arr3,arr4))
print(con)

[[1 2]
 [5 6]
 [4 5]
 [7 8]]


In [102]:
con=np.hstack((arr3,arr4))
print(con)

[[1 2 4 5]
 [5 6 7 8]]


In [103]:
arr=np.arange(10)
sp=np.split(arr,[4,7])
print(sp)

[array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [119]:
arr=np.arange(24).reshape(6,4)
print(arr)
sp=np.split(arr,2,axis=1)
print(sp)
sp=np.split(arr,[3,5],axis=0)
print(sp)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19]]), array([[20, 21, 22, 23]])]


In [120]:
sp=np.vsplit(arr,[1,3])
print(sp)
sp=np.hsplit(arr,4)
print(sp)

[array([[0, 1, 2, 3]]), array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])]


In [123]:
print(np.sqrt([2,5,67]))
print(np.exp([5,6,7]))
print(np.argmax([7,3,9]))# index of max
print(np.max([5,3,6]))

[1.41421356 2.23606798 8.18535277]
[ 148.4131591   403.42879349 1096.63315843]
2
6


In [135]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])

print(np.add(arr1,arr2))
print(np.divide(arr1,arr2))
print(arr1+arr2)
print(arr2%arr1)# remian     
print(arr2//arr1)# multiple
print(arr2**arr1)# power

[5 7 9]
[0.25 0.4  0.5 ]
[5 7 9]
[0 1 0]
[4 2 2]
[  4  25 216]


In [136]:
# times matrix
a=np.array([[1,2],[5,6]])
b=np.array([[4,5],[7,8]])
print(a@b)

[[18 21]
 [62 73]]


In [143]:
arr=np.arange(12).reshape(3,4)
view=arr[0:2]
print(view)
view[0,0]=999
print(view)
print(arr)# oraginal data is motified  

[[0 1 2 3]
 [4 5 6 7]]
[[999   1   2   3]
 [  4   5   6   7]]
[[999   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


In [144]:
arr=np.arange(12).reshape(3,4)
view=arr[0:2].copy()# copy to a brand new data
print(view)
view[0,0]=999
print(view)
print(arr)

[[0 1 2 3]
 [4 5 6 7]]
[[999   1   2   3]
 [  4   5   6   7]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
