In [2]:
import pandas as pd
import numpy as np

In [3]:
np. __version__

'2.2.6'

In [4]:
pd. __version__

'2.3.3'

In [5]:
!pip install --upgeade numpy


Usage:   
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: --upgeade


# duplicates

In [15]:
#duplicates
data={
    'name':['donna','jenny','zahra','mica','donna'],
    'age':['22','23','24','21','22'],
    'city':['kl','jb','la','kl','kl']
}
df=pd.DataFrame(data)
print(df.duplicated())
print(df.drop_duplicates())


0    False
1    False
2    False
3    False
4     True
dtype: bool
    name age city
0  donna  22   kl
1  jenny  23   jb
2  zahra  24   la
3   mica  21   kl


In [19]:
#subset duplicates
data={
    'name':['donna','jenny','zahra','mica','donna'],
    'age':['22','23','24','21','22'],
    'city':['kl','jb','la','kl','kl2']
}
df=pd.DataFrame(data)
print(df.duplicated(subset='name',keep='first'))
drop=df.duplicated(subset='name',keep='first')
print(df[~drop])

0    False
1    False
2    False
3    False
4     True
dtype: bool
    name age city
0  donna  22   kl
1  jenny  23   jb
2  zahra  24   la
3   mica  21   kl


# missing

In [33]:
data={
    'a':[1,2,None,4],
    'b':[np.nan,2,3,4],
    'c':['na','valid',None,'missing']
}
df=pd.DataFrame(data)
print(df.isna())
print(df.isnull())
print(df.notna())

       a      b      c
0  False   True  False
1  False  False  False
2   True  False   True
3  False  False  False
       a      b      c
0  False   True  False
1  False  False  False
2   True  False   True
3  False  False  False
       a      b      c
0   True  False   True
1   True   True   True
2  False   True  False
3   True   True   True


In [29]:
df['c']=df['c'].replace('na',None)
df

,a,b,c
0,1.0,NaN,None
1,2.0,2.0,valid
2,NaN,3.0,None
3,4.0,4.0,missing


In [35]:
#delet all of columns which contains missing value
df1=df.dropna(axis=1)
df1

#delet all of columns which contains missing value
df2=df.dropna(axis=0)
df2

#delet rows with missing value in specific columns
df3=df.dropna(subset=['a'],axis=0)
df3

,a,b,c
0,1.0,NaN,na
1,2.0,2.0,valid
3,4.0,4.0,missing


In [39]:
#fill with a specific value
df1=df.fillna(0)
print(df1)

#fill with the previous value
df2=df.ffill()
print(df2)

#fill with the next value
df3=df.bfill()
print(df3)

#fill by linear model
#df4=df.interpolation(method='linear')
#df4

     a    b        c
0  1.0  0.0       na
1  2.0  2.0    valid
2  0.0  3.0        0
3  4.0  4.0  missing
     a    b        c
0  1.0  NaN       na
1  2.0  2.0    valid
2  2.0  3.0    valid
3  4.0  4.0  missing
     a    b        c
0  1.0  2.0       na
1  2.0  2.0    valid
2  4.0  3.0  missing
3  4.0  4.0  missing


# replace

In [53]:
data={
    'a':[1,2,3,4],
    'b':['apple','banana','pear','passionfruit']
}
df=pd.DataFrame(data)
print(df)

   a             b
0  1         apple
1  2        banana
2  3          pear
3  4  passionfruit


In [54]:
df['c']=df['b'].replace('apple','watermelom')
df['d']=df['b'].replace(['apple','pear'],'orange')
df['e']=df['b'].replace({'apple':'watermelom','pear':'fruit'})
df

,a,b,c,d,e
0,1,apple,watermelom,orange,watermelom
1,2,banana,banana,banana,banana
2,3,pear,pear,orange,fruit
3,4,passionfruit,passionfruit,passionfruit,passionfruit


# apply&map

In [60]:
data={
    'name':['donna','mica','zahra'],
    'weight':[56,45,65],
    'height':[1.67,1.57,1.77]
}
df=pd.DataFrame(data)
df

,name,weight,height
0,donna,56,1.67
1,mica,45,1.57
2,zahra,65,1.77


In [61]:
def bmi(r):
    bmi=r['weight']/r['height']**2
    return bmi
df['bmi']=df.apply(bmi,axis=1)
print(df)

    name  weight  height        bmi
0  donna      56    1.67  20.079601
1   mica      45    1.57  18.256319
2  zahra      65    1.77  20.747550


In [73]:
df.iloc[:,1:4].apply(sum,axis=1)

0    77.749601
1    64.826319
2    87.517550
dtype: float64

In [76]:
df=pd.DataFrame({
    'fruit':['apple','pear','banana']
})
cate={'apple':'imported','pear':'imported','banana':'local'}
df['type']=df['fruit'].map(cate)
df

,fruit,type
0,apple,imported
1,pear,imported
2,banana,local


# outliers

In [103]:
df=pd.DataFrame({'value':[3343,3256,3643,999,3322,3345,3224,3451,3641]})
print(df)

mean=df['value'].mean()
std=df['value'].std()
upper=mean+3*std
lower=mean-3*std

out=(df['value']>upper)|(df['value']<lower)
print(out)

   value
0   3343
1   3256
2   3643
3    999
4   3322
5   3345
6   3224
7   3451
8   3641
0    False
1    False
2    False
3    False
4    False
5    False
6    False
7    False
8    False
Name: value, dtype: bool


In [101]:
df['value']=np.where(out,999,df['value'])
df

,value
0,3343
1,3256
2,3643
3,34
4,3322
5,3345
6,3224
7,3451
8,3641


## exercise

In [126]:
data=pd.read_csv('census.csv')
data.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
0,40,3,6,1,0,Alabama,Alabama,4779736,4780127,4785161,...,0.002295,-0.193196,0.381066,0.582002,-0.467369,1.030015,0.826644,1.383282,1.724718,0.712594
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243286,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861


In [128]:
data50=data[data['SUMLEV']==50]
data50.head()

,SUMLEV,REGION,DIVISION,STATE,COUNTY,STNAME,CTYNAME,CENSUS2010POP,ESTIMATESBASE2010,POPESTIMATE2010,...,RDOMESTICMIG2011,RDOMESTICMIG2012,RDOMESTICMIG2013,RDOMESTICMIG2014,RDOMESTICMIG2015,RNETMIG2011,RNETMIG2012,RNETMIG2013,RNETMIG2014,RNETMIG2015
1,50,3,6,1,1,Alabama,Autauga County,54571,54571,54660,...,7.242091,-2.915927,-3.012349,2.265971,-2.530799,7.606016,-2.626146,-2.722002,2.592270,-2.187333
2,50,3,6,1,3,Alabama,Baldwin County,182265,182265,183193,...,14.832960,17.647293,21.845705,19.243286,17.197872,15.844176,18.559627,22.727626,20.317142,18.293499
3,50,3,6,1,5,Alabama,Barbour County,27457,27457,27341,...,-4.728132,-2.500690,-7.056824,-3.904217,-10.543299,-4.874741,-2.758113,-7.167664,-3.978583,-10.543299
4,50,3,6,1,7,Alabama,Bibb County,22915,22919,22861,...,-5.527043,-5.068871,-6.201001,-0.177537,0.177258,-5.088389,-4.363636,-5.403729,0.754533,1.107861
5,50,3,6,1,9,Alabama,Blount County,57322,57322,57373,...,1.807375,-1.177622,-1.748766,-2.062535,-1.369970,1.859511,-0.848580,-1.402476,-1.577232,-0.884411


In [138]:
data50.columns.tolist()

['SUMLEV',
 'REGION',
 'DIVISION',
 'STATE',
 'COUNTY',
 'STNAME',
 'CTYNAME',
 'CENSUS2010POP',
 'ESTIMATESBASE2010',
 'POPESTIMATE2010',
 'POPESTIMATE2011',
 'POPESTIMATE2012',
 'POPESTIMATE2013',
 'POPESTIMATE2014',
 'POPESTIMATE2015',
 'NPOPCHG_2010',
 'NPOPCHG_2011',
 'NPOPCHG_2012',
 'NPOPCHG_2013',
 'NPOPCHG_2014',
 'NPOPCHG_2015',
 'BIRTHS2010',
 'BIRTHS2011',
 'BIRTHS2012',
 'BIRTHS2013',
 'BIRTHS2014',
 'BIRTHS2015',
 'DEATHS2010',
 'DEATHS2011',
 'DEATHS2012',
 'DEATHS2013',
 'DEATHS2014',
 'DEATHS2015',
 'NATURALINC2010',
 'NATURALINC2011',
 'NATURALINC2012',
 'NATURALINC2013',
 'NATURALINC2014',
 'NATURALINC2015',
 'INTERNATIONALMIG2010',
 'INTERNATIONALMIG2011',
 'INTERNATIONALMIG2012',
 'INTERNATIONALMIG2013',
 'INTERNATIONALMIG2014',
 'INTERNATIONALMIG2015',
 'DOMESTICMIG2010',
 'DOMESTICMIG2011',
 'DOMESTICMIG2012',
 'DOMESTICMIG2013',
 'DOMESTICMIG2014',
 'DOMESTICMIG2015',
 'NETMIG2010',
 'NETMIG2011',
 'NETMIG2012',
 'NETMIG2013',
 'NETMIG2014',
 'NETMIG2015',
 'RES

In [147]:
subdata1=data50.loc[:,['STNAME', 'CTYNAME', 'BIRTHS2010', 'BIRTHS2010', 'BIRTHS2012', 'BIRTHS2013', 'BIRTHS2014', 'BIRTHS2015','POPESTIMATE2010', 'POPESTIMATE2011', 'POPESTIMATE2012', 'POPESTIMATE2013', 'POPESTIMATE2014', 'POPESTIMATE2015']]
subdata1.head()


,STNAME,CTYNAME,BIRTHS2010,BIRTHS2010,BIRTHS2012,BIRTHS2013,BIRTHS2014,BIRTHS2015,POPESTIMATE2010,POPESTIMATE2011,POPESTIMATE2012,POPESTIMATE2013,POPESTIMATE2014,POPESTIMATE2015
1,Alabama,Autauga County,151,151,615,574,623,600,54660,55253,55175,55038,55290,55347
2,Alabama,Baldwin County,517,517,2092,2160,2186,2240,183193,186659,190396,195126,199713,203709
3,Alabama,Barbour County,70,70,300,283,260,269,27341,27226,27159,26973,26815,26489
4,Alabama,Bibb County,44,44,245,259,247,253,22861,22733,22642,22512,22549,22583
5,Alabama,Blount County,183,183,710,646,618,603,57373,57711,57776,57734,57658,57673


In [148]:
print(subdata1.shape)

(3142, 14)


## discretization

In [8]:
#equal ranges
data={'mark':[54,35,34,24,13,51,54]}
df=pd.DataFrame(data)
df

,mark
0,54
1,35
2,34
3,24
4,13
5,51
6,54


In [9]:
df['disc']=pd.cut(df['mark'],bins=3)
df

,mark,disc
0,54,"(40.333, 54.0]"
1,35,"(26.667, 40.333]"
2,34,"(26.667, 40.333]"
3,24,"(12.959, 26.667]"
4,13,"(12.959, 26.667]"
5,51,"(40.333, 54.0]"
6,54,"(40.333, 54.0]"


In [13]:
df['disc']=pd.cut(df['mark'],bins=[0,20,40,60,80,100])
df

,mark,disc
0,54,"(40, 60]"
1,35,"(20, 40]"
2,34,"(20, 40]"
3,24,"(20, 40]"
4,13,"(0, 20]"
5,51,"(40, 60]"
6,54,"(40, 60]"


In [14]:
df['cate']=pd.cut(df['mark'],bins=[0,20,40,60,80,100],labels=[1,2,3,4,5])
df

,mark,disc,cate
0,54,"(40, 60]",3
1,35,"(20, 40]",2
2,34,"(20, 40]",2
3,24,"(20, 40]",2
4,13,"(0, 20]",1
5,51,"(40, 60]",3
6,54,"(40, 60]",3


In [15]:
#equal frequencies
df['discq']=pd.qcut(df['mark'],q=4)
df

,mark,disc,cate,discq
0,54,"(40, 60]",3,"(52.5, 54.0]"
1,35,"(20, 40]",2,"(29.0, 35.0]"
2,34,"(20, 40]",2,"(29.0, 35.0]"
3,24,"(20, 40]",2,"(12.999, 29.0]"
4,13,"(0, 20]",1,"(12.999, 29.0]"
5,51,"(40, 60]",3,"(35.0, 52.5]"
6,54,"(40, 60]",3,"(52.5, 54.0]"


## permutation&sampling

In [16]:
arr=np.array([1,2,3,5,3,6,8,5])
np.random.seed(123)
per_arr=np.random.permutation(arr)
print(arr)
print(per_arr)

[1 2 3 5 3 6 8 5]
[1 2 5 5 3 3 6 8]


In [19]:
df=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':['a','s','d','f','g']})
per_df=df.sample(frac=1,random_state=123)
print(df)
print(per_df)

   A  B
0  1  a
1  2  s
2  3  d
3  4  f
4  5  g
   A  B
1  2  s
3  4  f
4  5  g
0  1  a
2  3  d


In [20]:
#sampling
arr=np.array([1,2,3,5,3,6,8,5])
np.random.seed(123)
se_arr=np.random.choice(arr,size=3,replace=False)
print(arr)
print(se_arr)

[1 2 3 5 3 6 8 5]
[1 2 5]


In [23]:
df=pd.DataFrame({
    'A':[1,2,3,4,5],
    'B':['a','s','d','f','g']})
se_df=df.sample(frac=0.4,random_state=123)
se_df2=df.sample(n=4,replace=True,random_state=123)
print(df)
print(se_df)
print(se_df2)

   A  B
0  1  a
1  2  s
2  3  d
3  4  f
4  5  g
   A  B
1  2  s
3  4  f
   A  B
2  3  d
4  5  g
2  3  d
1  2  s


## dummy_variables

In [25]:
df=pd.DataFrame({
    'A':[1,2,3,4,5],
    'category':['a','s','d','a','s']})
pd.get_dummies(df,columns=['category'],drop_first=False)

,A,category_a,category_d,category_s
0,1,True,False,False
1,2,False,False,True
2,3,False,True,False
3,4,True,False,False
4,5,False,False,True


## string_manipulation

In [38]:
text='good day'
print(text.lower())
print(text.upper())
print(text.capitalize())
print(text.title())
print(text.isdigit())
print('food'.isalpha())
print(text.isspace())
print(text.isupper())
print(text.islower())
print(text.istitle())

good day
GOOD DAY
Good day
Good Day
False
True
False
False
True
False


In [39]:
str='      hello         '
print(str.strip())
print(str.lstrip())
print(str.rstrip())

hello
hello         
      hello


In [45]:
print('hello'.find('hello'))
print('goot'.replace('t','d'))
print('a,s,d,f,g,'.split(','))

0
good
['a', 's', 'd', 'f', 'g', '']


In [49]:
df=pd.DataFrame({
    'name':['ali','donna','mica'],
    'cate':['good','great','nice']})
df['caten']=df['cate'].str.capitalize()
print(df)

    name   cate  caten
0    ali   good   Good
1  donna  great  Great
2   mica   nice   Nice


In [52]:
import re
text='bat cat rat mat'

#staring with b and c
print(re.findall(r'[bc]at',text))
print(re.findall(r'\W',text))

['bat', 'cat']
[' ', ' ', ' ']


In [61]:
data={'text':['hello  232--','ti g#ht123','abc$!9 87']}
df=pd.DataFrame(data)
print(df)

print(df['text'].str.replace(r'\d','X',regex=True))

           text
0  hello  232--
1    ti g#ht123
2     abc$!9 87
0    hello  XXX--
1      ti g#htXXX
2       abc$!X XX
Name: text, dtype: object


In [62]:
print(df['text'].str.replace(r'[^\w]',' ',regex=True))

0    hello  232  
1      ti g ht123
2       abc  9 87
Name: text, dtype: object


In [63]:
print(df['text'].str.replace(r'\s','_',regex=True))

0    hello__232--
1      ti_g#ht123
2       abc$!9_87
Name: text, dtype: object
